# Generated by Django 4.2.6 on 2023-10-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bibliography',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
