# Generated by Django 4.2.6 on 2023-10-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_bibliography'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bibliography',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
