# Generated by Django 4.2.6 on 2023-10-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bibliography',
            field=models.TextField(blank=True, default='Add a bio to your profile', max_length=500),
        ),
    ]
