# Generated by Django 4.2.6 on 2023-10-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_bibliography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bibliography',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
