# Generated by Django 4.2.6 on 2023-10-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_bibliography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bibliography',
            new_name='biography',
        ),
    ]
