# Generated by Django 4.2.6 on 2023-10-28 00:57

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_rename_bibliography_profile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profiles/default_user.jpg', upload_to='profiles'),
        ),
    ]
